SELECT
  CASE
    WHEN utm_source = 'sin.creativecdn.com' THEN 'sin.creativecdn.com'
    WHEN utm_source = 'ads.as.criteo.com' THEN 'criteo'
    WHEN utm_source = 'mall.pitsquare.jp' THEN 'もらっトク！モール'
    WHEN utm_source = 'criteo.com' THEN 'criteo'
    WHEN utm_source = 'aax-fe-sin.amazon-adsystem.com' THEN 'Amazon'
    WHEN utm_source = 'www.jr-tgm.com' THEN 'JR Takashimaya GATETOWER MALL'
    WHEN utm_source = 'www.porta.co.jp' THEN 'Porta京都駅地下街'
    WHEN utm_source = 'www.0101.co.jp' THEN 'OIOI'
    WHEN utm_source = 'www.ginza-inz.co.jp' THEN 'GINZA INZ'
    WHEN utm_source = 'paid.outbrain.com' THEN 'outbrain'
    WHEN utm_source = 'outlook.live.com' THEN 'Outlook'
    WHEN utm_source = 'www.go1buy1.com' THEN 'Go1Buy1'
    WHEN utm_source = 'www.lumine.ne.jp' THEN 'LUMINE'
    WHEN utm_source = 'emifull.jp' THEN 'エミフルMASAKI'
    WHEN utm_source = 'connect.auone.jp' THEN 'auone'
    WHEN utm_source = 'mitsui-shopping-park.com' THEN '三井ショッピングパーク'
    WHEN utm_source = 'www.tenchika.com' THEN '天神地下街'
    WHEN utm_source = 'sbd-chat.ok-sky.com' THEN 'WEB接客OK SKY'
    WHEN utm_source = 's.kakaku.com' THEN '価格.com'
    WHEN utm_source = 'payments.amazon.co.jp' THEN 'amazon pay'
    WHEN utm_source = 'adtdp.com' THEN 'adtecstudio|サイバーエージェント'
    WHEN utm_source = 'fep.sps-system.com' THEN 'クレジットカード(SBPS)'
    WHEN utm_source = 'www.rebates.jp' THEN 'Rakuten Rebates'
    WHEN utm_source = 'www.lucua.jp' THEN 'LUCUA osaka'
    WHEN utm_source = 'www.e-paseode.com' THEN 'JP TOWER paseo'
    WHEN utm_source = '4meee.com' THEN '4MEEE'
    WHEN utm_source = 'www.takasakitb.co.jp' THEN 'TAKASAKI TERMINAL BUILDING'
    WHEN utm_source = 'admin.karte.io' THEN 'Karte'
    WHEN utm_source = 'sun-ste.com' THEN 'さんすて'
    WHEN utm_source = 'ad.as.amanad.adtdp.com' THEN 'adtecstudio|サイバーエージェント'
    WHEN utm_source = 'www.karuizawa-psp.jp' THEN '軽井沢プリンスショッピングプラザ'
    WHEN utm_source = 'www.h-sanbangai.com' THEN '阪急三番街'
    WHEN utm_source = 'www.stellarplace.net' THEN 'JP TOWER STELLAR PLACE'
    WHEN utm_source = 'www.atre.co.jp' THEN 'Atre'
    WHEN utm_source = 'mail.ocn.jp' THEN 'OCNメール'
    WHEN utm_source = 'tamaru.eposcard.co.jp' THEN 'EPOSポイントUPサイト'
    WHEN utm_source = 'www.ge-tokorozawa.com' THEN 'Grand Emio'
    WHEN utm_source = 'www.fesan-jp.com' THEN '盛岡駅ビルフェザン'
    WHEN utm_source = 'search.kakaku.com' THEN '価格.com'
    WHEN utm_source = 'www.nambacity.com' THEN 'namba CITY nankai'
    WHEN utm_source = 'keihan-mall.jp' THEN '京阪モール'
    WHEN utm_source = 'trc.taboola.com' THEN 'taboola'
    WHEN utm_source = 'creativecdn.com' THEN 'RTBHOUSE'
    WHEN utm_source = 'wm.sso.biglobe.ne.jp' THEN 'Biglobe'
    WHEN utm_source = 'www.granduo.jp' THEN 'グランデュオ'
    WHEN utm_source = 'admin.voice.zetacx.net' THEN 'ZETA VOICE|Admin'
    WHEN utm_source = 'kakaku.com' THEN '価格.com'
    WHEN utm_source = 'kuzuha-mall.com' THEN 'KUZUHA MALL'
    WHEN utm_source = 'riverside-senshu.com' THEN 'RIVERSIDE SENSHU'
    WHEN utm_source = 'karte-talk.io' THEN 'Karte'
    WHEN utm_source = 'themallsendai.com' THEN 'THE MALL仙台長町'
    WHEN utm_source = 'portal.auone.jp' THEN 'auone'
    WHEN utm_source = 'www.tennoji-mio.co.jp' THEN 'MIO TENNOJI'
    WHEN utm_source = 'www.mozo-wondercity.com' THEN 'mozo wonder city'
    WHEN utm_source = 'tsukuba.iias.jp' THEN 'iias TSUKUBA'
    WHEN utm_source = 'www.parche.co.jp' THEN 'JR静岡駅ビルPARCHE'
    WHEN utm_source = 'shonan.terracemall.com' THEN 'TerraceMall湘南'
    WHEN utm_source = 'okazaki-aeonmall.com' THEN 'イオンモール岡崎'
    WHEN utm_source = 'go1buy1.com' THEN 'Go1Buy1'
    WHEN utm_source = 'yappli.plus' THEN 'Yappli'
    WHEN utm_source = 'www2.fashion-guide.jp' THEN 'FASHION(繊維/流行)GUIDE'
    WHEN utm_source LIKE '%google%' THEN 'Google'
    WHEN utm_source LIKE '%doubleclick%' THEN 'Google'
    WHEN utm_source = 'ampproject.org' THEN 'Google'
    WHEN utm_source LIKE '%google.android%' THEN 'Android'
    WHEN utm_source LIKE '%youtube%' THEN 'YouTube'
    WHEN utm_source LIKE '%yahoo%' THEN 'Yahoo!'
    WHEN utm_source = 's.yimg.jp' THEN 'Yahoo!'
    WHEN utm_source = 'yimg.jp' THEN 'Yahoo!'
    WHEN utm_source = 't.co' THEN 'Twitter'
    WHEN utm_source LIKE '%twitter%' THEN 'Twitter'
    WHEN utm_source LIKE '%facebook%' THEN 'Facebook'
    WHEN utm_source = 'l.messenger.com' THEN 'Facebook'
    WHEN utm_source LIKE '%instagram%' THEN 'Instagram'
    WHEN utm_source LIKE '%bing%' THEN 'bing'
    WHEN utm_source LIKE '%docomo%' THEN 'Docomo'
    WHEN utm_source = 'sp-web.search.auone.jp' THEN 'au'
    WHEN utm_source LIKE '%pinterest%' THEN 'Pinterest'
    WHEN utm_source = 'www.smartnews.com' THEN 'SmartNews'
    WHEN utm_source = 'gunosy.com' THEN 'gunosy'
    WHEN utm_source LIKE '%rakuten.co.jp' THEN 'Rakuten'
    WHEN utm_source = 'mobss.jword.jp' THEN 'jword'   
    WHEN utm_source = 'jwsearch.jword.jp' THEN 'jword'  
    WHEN utm_source LIKE '%line.me' THEN 'LINE'
    WHEN utm_source = 'antenna.jp' THEN 'antenna'
    WHEN utm_source = 'jp.antenna.app' THEN 'antenna'
    WHEN utm_source = 'newstopics.jp' THEN 'ニュートピ'
    WHEN utm_source = 'newspicks.com' THEN 'NewsPicks'
    WHEN utm_source = 'mixi.jp' THEN 'mixi'
    WHEN utm_source = 'goo.ne.jp' THEN 'goo'
    WHEN utm_source = 'news.goo.ne.jp' THEN 'goo'
    WHEN utm_source = 'search.goo.ne.jp' THEN 'goo'
    WHEN utm_source = 'green.goo.ne.jp' THEN 'goo'
    WHEN utm_source = 'green.search.goo.ne.jp' THEN 'goo'
    WHEN utm_source = 'news-goo-ne-jp.cdn.ampproject.org' THEN 'goo'
    WHEN utm_source LIKE '%excite.co.jp' THEN 'excite'
    WHEN utm_source LIKE '%nifty.com' THEN 'nifty'
    WHEN utm_source = 'cgi.search.biglobe.ne.jp' THEN 'Biglobe'
    WHEN utm_source = 'biglobe.ne.jp' THEN 'Biglobe'
    WHEN utm_source = 'www.so-net.ne.jp' THEN 'so-net'
    WHEN utm_source = '%ocn.jp' THEN 'Ocn'
    WHEN utm_source = 'googleads.g.doubleclick.net' THEN 'GoogleAds'
    WHEN utm_source = 'duckduckgo.com' THEN 'DuckDuckGo'
    WHEN utm_source = 'nortonsafe.search.ask.com' THEN 'NortonSafeSearch'
    WHEN utm_source = 'feedly.com' THEN 'Feedly'    
    WHEN utm_source = 'com.twitpane' THEN 'TwitPane'    
    WHEN utm_source = 'www.linkedin.com' THEN 'Linkedin'
    WHEN utm_source = 'note.com' THEN 'Note'  
    WHEN utm_source = 'note.mu' THEN 'Note'
    WHEN utm_source = 'com.slack' THEN 'slack'
    WHEN utm_source LIKE '%popin.cc' THEN 'popIn'
    WHEN utm_source LIKE '%logly.co.jp' THEN 'LOGLY'
    WHEN utm_source = 'transition.meltwater.com' THEN 'Meltwater'  
    WHEN utm_source = 'may.2chan.net' THEN 'ふたばちゃんねる'  
    WHEN utm_source = 'ameblo.jp' THEN 'ameblo' 
    WHEN utm_source = 'prtimes.jp' THEN 'PR TIMES'    
    WHEN utm_source = 'prtimes-jp.cdn.ampproject.org' THEN 'PR TIMES'   
    WHEN utm_source = 'trilltrill.jp' THEN 'TRILL'
    WHEN utm_source = 'locari.jp' THEN 'Locari'
    WHEN utm_source = 'radiko.jp' THEN 'radiko'
    WHEN utm_source = 'rajiko.jp' THEN 'radiko'
    WHEN utm_source = 'news-radiko-jp.cdn.ampproject.org' THEN 'radiko'
    WHEN utm_source = 'b.hatena.ne.jp' THEN 'Hatena'
    WHEN utm_source = 't.pia.jp' THEN 'PIA'      
    WHEN utm_source = 'www.spotifypremium.jp' THEN 'Spotify'
    WHEN utm_source LIKE '%wikipedia.org' THEN 'wikipedia'
    WHEN utm_source = 'www.inoreader.com' THEN '　Inoreader'
    WHEN utm_source = 'rsch.jp' THEN 'リサーチパネル'
    WHEN utm_source = 'tmall.wamgame.jp' THEN 'Tモール'
    WHEN utm_source = 'aramame.net' THEN 'あらまめ2ch'
    WHEN utm_source = 'uzulife.biz' THEN 'NAPBIZ'
    WHEN utm_source = 'ad-contents.jp' THEN '簡単レシピ動画まとめ'
    WHEN utm_source = 'app.couples.lv' THEN 'COUPLES'
    WHEN utm_source = 'pokemon-matome.net' THEN 'ぽけりん'
    WHEN utm_source = 'bakusai.com' THEN '爆サイ.com'
    WHEN utm_source = 'm.one.impact-ad.jp' THEN 'MarketOne'
    WHEN utm_source = 'p-birthday' THEN 'Petit Birthday'
    WHEN utm_source = 'ast.client.jp' THEN 'DIVINATION★LINK'
    WHEN utm_source LIKE '%magazine-data.com' THEN 'ファッション雑誌ガイド'
    WHEN utm_source = 'patentsalon' THEN 'パテントサロン'
    WHEN utm_source LIKE '%macromill.com' THEN 'macromill' 
    WHEN utm_source LIKE '%msn.com' THEN 'msn'
    WHEN utm_source = 'taboola.com' THEN 'taboola'
    WHEN utm_source = 't.umblr' THEN 'tumblr'    
    WHEN utm_source LIKE '%outbrain' THEN 'Outbrain'
    WHEN utm_source = 'search.myway.com' THEN 'MyWay'
    WHEN utm_source = 'search.ask' THEN 'ask'
    WHEN utm_source = 'workplace' THEN 'workplace'    
    WHEN utm_source = 'surveymonkey' THEN 'surveymonkey'
    WHEN utm_source = 'sansan.com' THEN 'sansan'
    WHEN utm_source = 'cybozu.co.jp' THEN 'cybozu'
    WHEN utm_source LIKE '%surveymonkey.com' THEN 'surveymonkey'
    WHEN utm_source = 'www.chance.com' THEN 'チャンスイット'    
    WHEN utm_source = 'mv-sp.gsj.bz' THEN 'ミュージック ヴィレッジ'
    WHEN utm_source = 'speee-ad.akamaized.net' THEN 'SPEEE AD'
    WHEN utm_source = 'content-click.amanad.adtdp.com' THEN 'adtech studio(CA)'
    WHEN utm_source = 'www.knshow.com' THEN '懸賞生活'
    WHEN utm_source = 'news.mixi.jp' THEN 'mixiニュース'
    WHEN utm_source = 'www.arugoworks.net' THEN 'Arugoworks'    
    WHEN utm_source = 'www.ghibli.jp' THEN 'スタジオジブリ'
    WHEN utm_source = 'news.mynavi.jp' THEN 'マイナビニュース'
    WHEN utm_source = 'blog.livedoor.jp' THEN 'ライブドアブログ'
    WHEN utm_source = 'www.e-nexco.co.jp' THEN 'NEXCO東日本'    
    WHEN utm_source = 'www.ken-kaku.com' THEN '懸賞当確'
    WHEN utm_source = 'news.ameba.jp' THEN 'アメーバニュース'
    WHEN utm_source = 'news.livedoor.com' THEN 'ライブドアニュース'
    WHEN utm_source = 'itest.5ch.net' THEN '5ちゃんねる'    
    WHEN utm_source = 'radiotuner.jp' THEN 'ラジオ局周波数 全国版'
    WHEN utm_source = 'www.yoku-ataru.com' THEN 'よく当たるコム'
    WHEN utm_source = 'www.1101.com' THEN 'ほぼ日刊イトイ新聞'
    WHEN utm_source = 'admin-official.line.me' THEN 'LINE'
    WHEN utm_source = 'lineblog.me' THEN 'LINEブログ'
    WHEN utm_source = 'com.Slack' THEN 'slack'
    WHEN utm_source LIKE '%toutiao.com' THEN '今日头条'
    WHEN utm_source LIKE 'woman-excite-co-jp%' THEN 'ウーマンエキサイト'
    WHEN utm_source = 'lin.ee' THEN 'LINE'
    WHEN utm_source = 'ima.goo.ne.jp' THEN 'goo いまトピ'
    WHEN utm_source = '' THEN 'Non Referer' 
    WHEN utm_source is NULL THEN 'Non Referer' 
    WHEN utm_medium = 'form' THEN 'Form'
    ELSE 'Other'
  END AS channel_group,
  SUM(landing_score * cv_volume) landing_score,
  SUM(last_score * cv_volume) last_score,
  SUM(linear_score * cv_volume) linear_score,
FROM
  {{ref('attribution_06_result')}}
WHERE 0=0
  AND cv_flg = 0
GROUP BY 1